### ISSUE TITLE
Proxy error

### ISSUE THREAD

**Issue by Karh3030** [Mffff4/cityholderbot#2]
```
File "C:\Users\123\Downloads\cityholderbot\venv\Lib\site-packages\playwright\_impl\_connection.py", line 520, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.Error: BrowserType.launch: Browser does not support socks5 proxy authentication
```

Hi. I get this error when starting. Ok, I can create a proxy in https, but in what format? https://login:password:ip:port does not work, I get this error. And, if possible, will you attach a chromedriver to the git? Thank you.

**Comment by Mffff4** [comment]
Hello, I’ll start fixing most issues on 05.11. Thanks
