### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Inquisitor007** [Mffff4/cityholderbot#5]
Hello. Thanks for your work

The latest version gives this error

63|CityHolder  | 111 | Found city button using selector: //a[contains(@class, '_button_') and @href='/city']//div[contains(@class, '_title_') and (text()='Ваш город' or text()='Your City')]
63|CityHolder  | 07.11.2024 00:11
63|CityHolder  |  - 
63|CityHolder  | ERROR
63|CityHolder  |  - 
63|CityHolder  | 111 | Error after clicking city button: ElementHandle.click: Timeout 167000ms exceeded.
63|CityHolder  | Call log:
63|CityHolder  | attempting click action
63|CityHolder  |   -   waiting for element to be visible, enabled and stable
63|CityHolder  |   -   element is visible, enabled and stable
63|CityHolder  |   -   scrolling into view if needed
63|CityHolder  |   -   done scrolling
63|CityHolder  |   -   <div class="_dialogHolderComeBack_1mwk4_1">…</div> from <div class="_dialog_1lie3_1">…</div> subtree intercepts pointer events
63|CityHolder  |   - retrying click action, attempt #1
63|CityHolder  |   -   waiting for element to be visible, enabled and stable
63|CityHolder  |   -   element is visible, enabled and stable
63|CityHolder  |   -   scrolling into view if needed
63|CityHolder  |   -   done scrolling
63|CityHolder  |   -   <div class="_dialogHolderComeBack_1mwk4_1">…</div> from <div class="_dialog_1lie3_1">…</div> subtree intercepts pointer events

**Comment by Mffff4** [comment]
Fixed
