### ISSUE TITLE
The city is not upgraded. The balance is not spent

### ISSUE THREAD

**Issue by Inquisitor007** [Mffff4/cityholderbot#6]
Yesterday a problem appeared. The city is not upgraded. The balance is not spent

62|CityHolder  | 12.11.2024 13:03 - INFO - TEST | Found city button
62|CityHolder  | 12.11.2024 13:03 - INFO - TEST | Successfully navigated to city page
62|CityHolder  | 12.11.2024 13:08 - INFO - TEST | Found city button
62|CityHolder  | 12.11.2024 13:09 - INFO - TEST | Successfully navigated to city page
62|CityHolder  | 12.11.2024 13:14 - INFO - TEST | Starting city upgrade
62|CityHolder  | 12.11.2024 13:14 - ERROR - TEST | Error upgrading city: Page.wait_for_selector: Timeout 10000ms exceeded.
62|CityHolder  | Call log:
62|CityHolder  | waiting for locator("[class^=\"_buildNav\"]") to be visible
62|CityHolder  | 12.11.2024 13:14 - ERROR - TEST | Traceback: Traceback (most recent call last):
62|CityHolder  |   File "/home/mega/tgbots/CityHolder/bot/utils/webdriver_utils.py", line 130, in upgrade_city
62|CityHolder  |     await self.page.wait_for_selector('[class^="_buildNav"]', timeout=10000)
62|CityHolder  |   File "/home/mega/tgbots/CityHolder/venv/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 8158, in wait_for_selector
62|CityHolder  |     await self._impl_obj.wait_for_selector(
62|CityHolder  |   File "/home/mega/tgbots/CityHolder/venv/lib/python3.10/site-packages/playwright/_impl/_page.py", line 426, in wait_for_selector
62|CityHolder  |     return await self._main_frame.wait_for_selector(**locals_to_params(locals()))
62|CityHolder  |   File "/home/mega/tgbots/CityHolder/venv/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 323, in wait_for_selector
62|CityHolder  |     await self._channel.send("waitForSelector", locals_to_params(locals()))
62|CityHolder  |   File "/home/mega/tgbots/CityHolder/venv/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 59, in send
62|CityHolder  |     return await self._connection.wrap_api_call(
62|CityHolder  |   File "/home/mega/tgbots/CityHolder/venv/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 520, in wrap_api_call
62|CityHolder  |     raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
62|CityHolder  | playwright._impl._errors.TimeoutError: Page.wait_for_selector: Timeout 10000ms exceeded.
62|CityHolder  | Call log:
62|CityHolder  | waiting for locator("[class^=\"_buildNav\"]") to be visible
62|CityHolder  | 12.11.2024 13:14 - INFO - TEST | No upgrades available

**Comment by Mffff4** [comment]
Fixed
