### ISSUE TITLE
Same mistake again

### ISSUE THREAD

**Issue by Inquisitor007** [Mffff4/cityholderbot#7]
Same mistake again
Latest version

62|CityHolder  | 13.11.2024 17:36 - INFO - 9242424 | Found city button
62|CityHolder  | 13.11.2024 17:36 - INFO - 9242424 | Successfully navigated to city page
62|CityHolder  | 13.11.2024 17:39 - INFO - 9242424 | Found city button
62|CityHolder  | 13.11.2024 17:39 - INFO - 9242424 | Successfully navigated to city page
62|CityHolder  | 13.11.2024 17:42 - INFO - 9242424 | Starting city upgrade
62|CityHolder  | 13.11.2024 17:42 - ERROR - 
62|CityHolder  | 9242424 | Error upgrading city: Page.wait_for_selector: Timeout 10000ms exceeded.
62|CityHolder  | Call log:
62|CityHolder  | waiting for locator("[class^=\"_buildNav\"]") to be visible
62|CityHolder  | 13.11.2024 17:42 - ERROR - 9242424 | Traceback: Traceback (most recent call last):
62|CityHolder  |   File "/home/mega/tgbots/CityHolder/bot/utils/webdriver_utils.py", line 133, in upgrade_city
62|CityHolder  |     await self.page.wait_for_selector('[class^="_buildNav"]', timeout=10000)
62|CityHolder  |   File "/home/mega/tgbots/CityHolder/venv/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 8158, in wait_for_selector
62|CityHolder  |     await self._impl_obj.wait_for_selector(
62|CityHolder  |   File "/home/mega/tgbots/CityHolder/venv/lib/python3.10/site-packages/playwright/_impl/_page.py", line 426, in wait_for_selector
62|CityHolder  |     return await self._main_frame.wait_for_selector(**locals_to_params(locals()))
62|CityHolder  |   File "/home/mega/tgbots/CityHolder/venv/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 323, in wait_for_selector
62|CityHolder  |     await self._channel.send("waitForSelector", locals_to_params(locals()))
62|CityHolder  |   File "/home/mega/tgbots/CityHolder/venv/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 59, in send
62|CityHolder  |     return await self._connection.wrap_api_call(
62|CityHolder  |   File "/home/mega/tgbots/CityHolder/venv/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 520, in wrap_api_call
62|CityHolder  |     raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
62|CityHolder  | playwright._impl._errors.TimeoutError: Page.wait_for_selector: Timeout 10000ms exceeded.
62|CityHolder  | Call log:
62|CityHolder  | waiting for locator("[class^=\"_buildNav\"]") to be visible
62|CityHolder  | 13.11.2024 17:42 - INFO - 9242424 | No upgrades available
62|CityHolder  | 13.11.2024 17:42 - 
62|CityHolder  | INFO - 9242424 | Session ended
62|CityHolder  | 13.11.2024 17:42 - INFO - 9242424 | Session ended successfully
62|CityHolder  | 13.11.2024 17:42 - INFO - 9242424 | Session completed successfully
62|CityHolder  | 13.11.2024 17:42 - INFO - PSHIK | Thread timeout set: 999 seconds

**Comment by Tracker878** [comment]
same

**Comment by Mffff4** [comment]
git pull and use docker
